"""Adds pass_code in User schema

Revision ID: 2c5b68127bfa
Revises: 763b085736ad
Create Date: 2020-05-10 10:49:02.715667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5b68127bfa'
down_revision = '763b085736ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_code')
    # ### end Alembic commands ###
