"""Changes tablename blog to blogs

Revision ID: 763b085736ad
Revises: 5a8e4632f6d1
Create Date: 2020-05-09 22:10:15.992648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763b085736ad'
down_revision = '5a8e4632f6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='blog_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_pkey')
    )
    op.drop_table('blogs')
    # ### end Alembic commands ###
